@BASE_URL=http://localhost:8000/api/tasks

###
GET http://localhost:8000/api/tasks HTTP/1.1

###

POST http://localhost:8000/api/tasks HTTP/1.1
User-Agent: rest-client
Accept: application/json
Content-Type: application/x-www-form-urlencoded

title=hjhjhj&description=alalalal&completed=0


###
GET http://localhost:8000/api/tasks/9d96707a-b650-429b-9a4c-6eba6019ad44 HTTP/1.1

###
PUT http://localhost:8000/api/tasks/9d96707a-b650-429b-9a4c-6eba6019ad44 HTTP/1.1
User-Agent: rest-client
Accept: application/json
Content-Type: application/x-www-form-urlencoded

title=Sample&description=alalalal&completed=0

###
DELETE http://localhost:8000/api/tasks/9d9644c6-b438-4279-967e-dfe4bfafc1ad HTTP/1.1